INSERT INTO time (ID_TIME, NOME) VALUES (seq_time.nextval, 'CORINTHIANS');
INSERT INTO time (ID_TIME, NOME) VALUES (seq_time.nextval, 'PALMEIRAS');
INSERT INTO time (ID_TIME, NOME) VALUES (seq_time.nextval, 'SANTOS');

INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Felipe', '01-jan-1980', '10001', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Ricardo Silva', '01-jan-1981', '10002', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Roger Carvalho', '01-jan-1982', '1000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Marcus Winícius', '01-jan-1983', '10003', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Caíque', '01-jan-1984', '10000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Lucas Crispim', '01-jan-1985', '999', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Willians', '01-jan-1986', '1234', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alison', '01-jan-1987', '10000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Júnior Viçosa', '01-jan-1988', '10500', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Matheus Carvalho', '01-jan-1989', '16000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Luís Soares', '01-jan-1980', '10008', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Abner de Oliveira Simão', '01-jan-1980', '10001', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Acyr Rogerio Calcado', '01-jan-1981', '10002', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Adriano Valle de Sousa', '01-jan-1982', '1000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Adroaldo Da Cunha Portal', '01-jan-1983', '10003', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alan Elkinson Lopes De Lima', '01-jan-1984', '10000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alberto Silveira Brasil', '01-jan-1985', '999', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alexsandro Barros de Lima', '01-jan-1986', '1234', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Almir Correia Cardoso', '01-jan-1987', '10000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Angelo Luiz da Silva', '01-jan-1988', '10500', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Antonio Marcos Ricieri', '01-jan-1989', '16000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Andre Hamilton Abrantes', '01-jan-1980', '10008', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Benito Schaeffer Thomazelli', '01-jan-1980', '10001', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Bernardo Cunha Muniz', '01-jan-1981', '10002', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Carlos Martins', '01-jan-1982', '1000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Caic dos Santos Seccafim', '01-jan-1983', '10003', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Ciro de Lopes e Barbuda', '01-jan-1984', '10000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Claudio Takeshi Sato', '01-jan-1985', '999', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Clemerson Alexandr Krul', '01-jan-1986', '1234', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Clodovio de Paula Melo', '01-jan-1987', '10000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Daniel Rangel', '01-jan-1988', '10500', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Daniel Yoshito Ikejiri', '01-jan-1989', '16000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Claudio dos Santos Nogueira', '01-jan-1980', '10008', 3);

INSERT INTO TECNICO (ID_TECNICO, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_TECNICO.nextval, 'Marcelo Cabo', '01-jan-1970', '11000', 1);
INSERT INTO TECNICO (ID_TECNICO, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_TECNICO.nextval, 'Almir Correia Cardoso', '01-jan-1970', '11000', 2);
INSERT INTO TECNICO (ID_TECNICO, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_TECNICO.nextval, 'Eder Fernando Pedrazzi', '01-jan-1970', '11000', 3);

INSERT INTO JOGO (ID_JOGO, ID_TIME_A, ID_TIME_B)
VALUES (seq_jogo.nextval, 1, 2);
INSERT INTO JOGO (ID_JOGO, ID_TIME_A, ID_TIME_B)
VALUES (seq_jogo.nextval, 1, 3);
INSERT INTO JOGO (ID_JOGO, ID_TIME_A, ID_TIME_B)
VALUES (seq_jogo.nextval, 2, 3);

INSERT INTO CARTAO (ID_CARTAO, DESCRICAO) VALUES (seq_cartao.nextval, 'CARTÃO VERMELHO');
INSERT INTO CARTAO (ID_CARTAO, DESCRICAO) VALUES (seq_cartao.nextval, 'CARTÃO AMARELO');

INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,1);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,2);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,3);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,4);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,5);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,6);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,7);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,8);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,9);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,10);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,11);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,12);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,13);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,14);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,15);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,16);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,17);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,18);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,19);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,20);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,21);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,22);
