BEGIN
  DBMS_OUTPUT.PUT_LINE('Dropando Constraints');
  EXECUTE IMMEDIATE 'ALTER TABLE jogador DROP CONSTRAINT fk_time_jogador';
  EXECUTE IMMEDIATE 'ALTER TABLE tecnico DROP CONSTRAINT fk_time_tecnico';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo DROP CONSTRAINT fk_jogo_time_a';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo DROP CONSTRAINT fk_jogo_time_b';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador DROP CONSTRAINT fk_jj_jogo';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador DROP CONSTRAINT fk_jj_jogador';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador DROP CONSTRAINT uk_escalacao';
  EXECUTE IMMEDIATE 'ALTER TABLE gol DROP CONSTRAINT fk_gol_jj';
  EXECUTE IMMEDIATE 'ALTER TABLE gol DROP CONSTRAINT ck_gol_contra';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador_cartao DROP CONSTRAINT fk_jjc_jj';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador_cartao DROP CONSTRAINT fk_jjc_cartao';
  EXECUTE IMMEDIATE 'ALTER TABLE cartao DROP CONSTRAINT pk_cartao';
  EXECUTE IMMEDIATE 'ALTER TABLE gol DROP CONSTRAINT pk_gol';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador_cartao DROP CONSTRAINT pk_jjc';
  EXECUTE IMMEDIATE 'ALTER TABLE jogador DROP CONSTRAINT pk_jogador';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo DROP CONSTRAINT pk_jogo';
  EXECUTE IMMEDIATE 'ALTER TABLE jogo_jogador DROP CONSTRAINT pk_jogo_jogador';
  EXECUTE IMMEDIATE 'ALTER TABLE tecnico DROP CONSTRAINT pk_tecnico';
  EXECUTE IMMEDIATE 'ALTER TABLE time DROP CONSTRAINT pk_time';

EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('Dropando Sequences');
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_gol';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_cartao';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_jogador';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_jogo';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_jogo_jogador';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_jogo_jogador_cartao';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_tecnico';
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_time';

EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('Dropando Tables');
  EXECUTE IMMEDIATE 'DROP TABLE cartao';
  EXECUTE IMMEDIATE 'DROP TABLE gol';
  EXECUTE IMMEDIATE 'DROP TABLE jogador';
  EXECUTE IMMEDIATE 'DROP TABLE jogo';
  EXECUTE IMMEDIATE 'DROP TABLE jogo_jogador';
  EXECUTE IMMEDIATE 'DROP TABLE jogo_jogador_cartao';
  EXECUTE IMMEDIATE 'DROP TABLE tecnico';
  EXECUTE IMMEDIATE 'DROP TABLE time';

EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;

END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('Dropando Trigers');
  EXECUTE IMMEDIATE 'DROP TRIGGER TR_GOLS';

EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN
      RAISE;
    END IF;

END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('Dropando Functions e Procedures');
  EXECUTE IMMEDIATE 'DROP FUNCTION FNGOLSPORJOGADOR';

  EXECUTE IMMEDIATE 'DROP PROCEDURE PESCALAJOGADOR';
  EXECUTE IMMEDIATE 'DROP PROCEDURE PINSERECARTAO';
  EXECUTE IMMEDIATE 'DROP PROCEDURE PMARCACARTAO';
  EXECUTE IMMEDIATE 'DROP PROCEDURE PMARCAGOL';

EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

prompt -- Criando Base;

CREATE TABLE time(
  id_time NUMBER NOT NULL,
  nome VARCHAR2(400),
  CONSTRAINT pk_time PRIMARY KEY (id_time)
);

CREATE SEQUENCE seq_time
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO time (ID_TIME, NOME) VALUES (seq_time.nextval, 'CORINTHIANS');
INSERT INTO time (ID_TIME, NOME) VALUES (seq_time.nextval, 'PALMEIRAS');
INSERT INTO time (ID_TIME, NOME) VALUES (seq_time.nextval, 'SANTOS');

CREATE TABLE jogador(
  id_jogador NUMBER NOT NULL,
  nome VARCHAR2(400) NOT NULL,
  dt_nascimento DATE NOT NULL,
  salario NUMBER(18,2),
  id_time NUMBER NOT NULL,
  CONSTRAINT pk_jogador PRIMARY KEY (id_jogador),
  CONSTRAINT fk_time_jogador FOREIGN KEY (id_time) REFERENCES time(id_time)
);

CREATE SEQUENCE seq_jogador
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Felipe', '01-jan-1980', '10001', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Ricardo Silva', '01-jan-1981', '10002', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Roger Carvalho', '01-jan-1982', '1000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Marcus Winícius', '01-jan-1983', '10003', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Caíque', '01-jan-1984', '10000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Lucas Crispim', '01-jan-1985', '999', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Willians', '01-jan-1986', '1234', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alison', '01-jan-1987', '10000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Júnior Viçosa', '01-jan-1988', '10500', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Matheus Carvalho', '01-jan-1989', '16000', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Luís Soares', '01-jan-1980', '10008', 1);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Abner de Oliveira Simão', '01-jan-1980', '10001', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Acyr Rogerio Calcado', '01-jan-1981', '10002', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Adriano Valle de Sousa', '01-jan-1982', '1000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Adroaldo Da Cunha Portal', '01-jan-1983', '10003', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alan Elkinson Lopes De Lima', '01-jan-1984', '10000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alberto Silveira Brasil', '01-jan-1985', '999', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Alexsandro Barros de Lima', '01-jan-1986', '1234', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Almir Correia Cardoso', '01-jan-1987', '10000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Angelo Luiz da Silva', '01-jan-1988', '10500', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Antonio Marcos Ricieri', '01-jan-1989', '16000', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Andre Hamilton Abrantes', '01-jan-1980', '10008', 2);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Benito Schaeffer Thomazelli', '01-jan-1980', '10001', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Bernardo Cunha Muniz', '01-jan-1981', '10002', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Carlos Martins', '01-jan-1982', '1000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Caic dos Santos Seccafim', '01-jan-1983', '10003', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Ciro de Lopes e Barbuda', '01-jan-1984', '10000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Claudio Takeshi Sato', '01-jan-1985', '999', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Clemerson Alexandr Krul', '01-jan-1986', '1234', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Clodovio de Paula Melo', '01-jan-1987', '10000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Daniel Rangel', '01-jan-1988', '10500', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Daniel Yoshito Ikejiri', '01-jan-1989', '16000', 3);
INSERT INTO JOGADOR (ID_JOGADOR, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_JOGADOR.nextval, 'Claudio dos Santos Nogueira', '01-jan-1980', '10008', 3);

CREATE TABLE tecnico(
  id_tecnico NUMBER NOT NULL,
  nome VARCHAR2(400) NOT NULL,
  dt_nascimento DATE NOT NULL,
  salario NUMBER(18,2),
  id_time NUMBER NOT NULL,
  CONSTRAINT pk_tecnico PRIMARY KEY (id_tecnico),
  CONSTRAINT fk_time_tecnico FOREIGN KEY (id_time) REFERENCES  time (id_time)
);

CREATE SEQUENCE seq_tecnico
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO TECNICO (ID_TECNICO, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_TECNICO.nextval, 'Marcelo Cabo', '01-jan-1970', '11000', 1);
INSERT INTO TECNICO (ID_TECNICO, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_TECNICO.nextval, 'Almir Correia Cardoso', '01-jan-1970', '11000', 2);
INSERT INTO TECNICO (ID_TECNICO, NOME, DT_NASCIMENTO, SALARIO, ID_TIME)
VALUES (SEQ_TECNICO.nextval, 'Eder Fernando Pedrazzi', '01-jan-1970', '11000', 3);

CREATE TABLE jogo(
  id_jogo NUMBER NOT NULL,
  id_time_a NUMBER NOT NULL,
  id_time_b NUMBER NOT NULL,
  nr_gol_a NUMBER,
  nr_gol_b NUMBER,
  dh_inicio DATE,
  dh_fim DATE,
  CONSTRAINT pk_jogo PRIMARY KEY (id_jogo),
  CONSTRAINT fk_jogo_time_a FOREIGN KEY (id_time_a) REFERENCES time (id_time),
  CONSTRAINT fk_jogo_time_b FOREIGN KEY (id_time_b) REFERENCES time (id_time)
);

CREATE SEQUENCE seq_jogo
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO JOGO (ID_JOGO, ID_TIME_A, ID_TIME_B, NR_GOL_A, NR_GOL_B)
VALUES (seq_jogo.nextval, 1, 2, 0, 0);

INSERT INTO JOGO (ID_JOGO, ID_TIME_A, ID_TIME_B, NR_GOL_A, NR_GOL_B)
VALUES (seq_jogo.nextval, 1, 3, 0, 0);

INSERT INTO JOGO (ID_JOGO, ID_TIME_A, ID_TIME_B, NR_GOL_A, NR_GOL_B)
VALUES (seq_jogo.nextval, 2, 3, 0, 0);

CREATE TABLE cartao (
  id_cartao NUMBER NOT NULL,
  descricao VARCHAR2(400) NOT NULL,
  qtde NUMBER DEFAULT 1,
  CONSTRAINT pk_cartao PRIMARY KEY (id_cartao)
);

CREATE SEQUENCE seq_cartao
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO CARTAO (ID_CARTAO, DESCRICAO) VALUES (seq_cartao.nextval, 'CARTÃO VERMELHO');
INSERT INTO CARTAO (ID_CARTAO, DESCRICAO) VALUES (seq_cartao.nextval, 'CARTÃO AMARELO');

CREATE TABLE jogo_jogador (
  id_jogo_jogador NUMBER NOT NULL,
  id_jogo NUMBER NOT NULL,
  id_jogador NUMBER NOT NULL,
  CONSTRAINT pk_jogo_jogador PRIMARY KEY (id_jogo_jogador),
  CONSTRAINT fk_jj_jogo FOREIGN KEY (id_jogo) REFERENCES jogo (id_jogo),
  CONSTRAINT fk_jj_jogador FOREIGN KEY (id_jogador) REFERENCES jogador (id_jogador),
  CONSTRAINT uk_escalacao UNIQUE (id_jogo, id_jogador)
);

CREATE SEQUENCE seq_jogo_jogador
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,1);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,2);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,3);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,4);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,5);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,6);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,7);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,8);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,9);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,10);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,11);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,12);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,13);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,14);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,15);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,16);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,17);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,18);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,19);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,20);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,21);
INSERT INTO JOGO_JOGADOR (ID_JOGO_JOGADOR, ID_JOGO, ID_JOGADOR) VALUES (seq_jogo_jogador.nextval,1,22);

CREATE TABLE gol (
  id_gol NUMBER NOT NULL,
  id_jogo_jogador NUMBER NOT NULL,
  contra CHAR(1) NOT NULL,
  CONSTRAINT pk_gol PRIMARY KEY (id_gol),
  CONSTRAINT fk_gol_jj FOREIGN KEY (id_jogo_jogador) REFERENCES jogo_jogador (id_jogo_jogador),
  CONSTRAINT ck_gol_contra CHECK (contra = 'S' OR contra = 'N')
);

CREATE SEQUENCE seq_gol
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE jogo_jogador_cartao (
  id_jogo_jogador_cartao NUMBER NOT NULL,
  id_jogo_jogador NUMBER NOT NULL,
  id_cartao NUMBER NOT NULL,
  CONSTRAINT pk_jjc PRIMARY KEY (id_jogo_jogador),
  CONSTRAINT fk_jjc_jj FOREIGN KEY (id_jogo_jogador) REFERENCES jogo_jogador (id_jogo_jogador),
  CONSTRAINT fk_jjc_cartao FOREIGN KEY (id_cartao) REFERENCES cartao (id_cartao)
);

CREATE SEQUENCE seq_jogo_jogador_cartao
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;